backend:
  name: git-gateway
  branch: main  # or 'master' depending on your repo

media_folder: "jonathanBeard/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "jonathanBeard/index.html"
        fields:
          - {label: "Intro Text", name: "body", widget: "markdown"}
